// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uerrwzyxiepcltnlztft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlcnJ3enl4aWVwY2x0bmx6dGZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NzM4NjAsImV4cCI6MjA2OTU0OTg2MH0.gdKNWybEBEnkOkHgESDCb8SE6ITmBuc8AKIaa1xvrcQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});